(function (){var g=!0,i=null,j=!1,l=encodeURIComponent,m=window,n=Error,aa=parseInt,p=String,q=document,r=Array;function s(a,b){return a.innerHTML=b}function ba(a,b){return a.currentTarget=b}function ca(a,b){return a.className=b}var v="appendChild",w="push",x="slice",z="replace",A="indexOf",da="createElement",B="firstChild",ea="setAttribute",C="type",D="substr",E="length",fa="propertyIsEnumerable",ga="title",F="prototype",G="split",ha="location",H="call",ia="href",ja="apply",I="join",ka="alternate",J;var K=this;function la(){}function ma(a){a.F=function(){return a.ca?a.ca:a.ca=new a}}
function na(a){var b=typeof a;if("object"==b)if(a){if(a instanceof r)return"array";if(a instanceof Object)return b;var c=Object[F].toString[H](a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a[E]&&"undefined"!=typeof a.splice&&"undefined"!=typeof a[fa]&&!a[fa]("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a[H]&&"undefined"!=typeof a[fa]&&!a[fa]("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a[H])return"object";
return b}function oa(a){var b=na(a);return"array"==b||"object"==b&&"number"==typeof a[E]}function L(a){return"string"==typeof a}function pa(a){return"function"==na(a)}function qa(a){var b=typeof a;return"object"==b&&a!=i||"function"==b}function ra(a){return a[sa]||(a[sa]=++ta)}var sa="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ta=0;function ua(a,b){var c=r[F][x][H](arguments,1);return function(){var d=r[F][x][H](arguments);d.unshift[ja](d,c);return a[ja](this,d)}}
function M(a,b){function c(){}c.prototype=b[F];a.u=b[F];a.prototype=new c;a[F].constructor=a}function va(a,b){if(b)return a[z](wa,"&amp;")[z](xa,"&lt;")[z](ya,"&gt;")[z](za,"&quot;");if(!Aa.test(a))return a;-1!=a[A]("&")&&(a=a[z](wa,"&amp;"));-1!=a[A]("<")&&(a=a[z](xa,"&lt;"));-1!=a[A](">")&&(a=a[z](ya,"&gt;"));-1!=a[A]('"')&&(a=a[z](za,"&quot;"));return a}var wa=/&/g,xa=/</g,ya=/>/g,za=/\"/g,Aa=/[&<>\"]/;
function Ba(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=q[da]("div");return a[z](Ca,function(d,f){var e=b[d];if(e)return e;if("#"==f.charAt(0)){var h=Number("0"+f[D](1));isNaN(h)||(e=p.fromCharCode(h))}e||(s(c,d+" "),e=c[B].nodeValue[x](0,-1));return b[d]=e})}
function Da(a){return a[z](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=Number("0"+c[D](1));if(!isNaN(d))return p.fromCharCode(d)}return b}})}
var Ca=/&([^;\s<&]+);?/g,N=r[F],Ea=N[A]?function(a,b,c){return N[A][H](a,b,c)}:function(a,b,c){c=c==i?0:0>c?Math.max(0,a[E]+c):c;if(L(a))return!L(b)||1!=b[E]?-1:a[A](b,c);for(;c<a[E];c++)if(c in a&&a[c]===b)return c;return-1},Fa=N.forEach?function(a,b,c){N.forEach[H](a,b,c)}:function(a,b,c){for(var d=a[E],f=L(a)?a[G](""):a,e=0;e<d;e++)e in f&&b[H](c,f[e],e,a)},Ga=N.filter?function(a,b,c){return N.filter[H](a,b,c)}:function(a,b,c){for(var d=a[E],f=[],e=0,h=L(a)?a[G](""):a,k=0;k<d;k++)if(k in h){var o=
h[k];b[H](c,o,k,a)&&(f[e++]=o)}return f},Ha=N.every?function(a,b,c){return N.every[H](a,b,c)}:function(a,b,c){for(var d=a[E],f=L(a)?a[G](""):a,e=0;e<d;e++)if(e in f&&!b[H](c,f[e],e,a))return j;return g};function O(a,b){return 0<=Ea(a,b)}function Ia(a,b){var c=Ea(a,b),d;(d=0<=c)&&N.splice[H](a,c,1);return d}function Ja(a){var b=a[E];if(0<b){for(var c=r(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ka(a,b,c){return 2>=arguments[E]?N[x][H](a,b):N[x][H](a,b,c)}var La;
function Ma(a){a=a.className;return L(a)&&a.match(/\S+/g)||[]}function Na(a,b){for(var c=Ma(a),d=Ka(arguments,1),f=c[E]+d[E],e=c,h=0;h<d[E];h++)O(e,d[h])||e[w](d[h]);ca(a,c[I](" "));return c[E]==f}function Oa(a,b){var c=Ma(a),d=Ka(arguments,1),f=Pa(c,d);ca(a,f[I](" "));return f[E]==c[E]-d[E]}function Pa(a,b){return Ga(a,function(c){return!O(b,c)})}function Qa(a,b,c){for(var d in a)b[H](c,a[d],d,a)}var Ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Sa(a,b){for(var c,d,f=1;f<arguments[E];f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Ra[E];e++)c=Ra[e],Object[F].hasOwnProperty[H](d,c)&&(a[c]=d[c])}}var P,Ta,Ua,Va;function Wa(){return K.navigator?K.navigator.userAgent:i}Va=Ua=Ta=P=j;var Xa;if(Xa=Wa()){var Ya=K.navigator;P=0==Xa[A]("Opera");Ta=!P&&-1!=Xa[A]("MSIE");Ua=!P&&-1!=Xa[A]("WebKit");Va=!P&&!Ua&&"Gecko"==Ya.product}var Za=P,Q=Ta,$a=Va,ab=Ua,bb;
a:{var cb="",db;if(Za&&K.opera)var eb=K.opera.version,cb="function"==typeof eb?eb():eb;else if($a?db=/rv\:([^\);]+)(\)|;)/:Q?db=/MSIE\s+([^\);]+)(\)|;)/:ab&&(db=/WebKit\/(\S+)/),db)var fb=db.exec(Wa()),cb=fb?fb[1]:"";if(Q){var gb,hb=K.document;gb=hb?hb.documentMode:void 0;if(gb>parseFloat(cb)){bb=p(gb);break a}}bb=cb}var ib=bb,jb={};
function R(a){var b;if(!(b=jb[a])){b=0;for(var c=p(ib)[z](/^[\s\xa0]+|[\s\xa0]+$/g,"")[G]("."),d=p(a)[z](/^[\s\xa0]+|[\s\xa0]+$/g,"")[G]("."),f=Math.max(c[E],d[E]),e=0;0==b&&e<f;e++){var h=c[e]||"",k=d[e]||"",o=RegExp("(\\d*)(\\D*)","g"),t=RegExp("(\\d*)(\\D*)","g");do{var u=o.exec(h)||["","",""],y=t.exec(k)||["","",""];if(0==u[0][E]&&0==y[0][E])break;b=((0==u[1][E]?0:aa(u[1],10))<(0==y[1][E]?0:aa(y[1],10))?-1:(0==u[1][E]?0:aa(u[1],10))>(0==y[1][E]?0:aa(y[1],10))?1:0)||((0==u[2][E])<(0==y[2][E])?
-1:(0==u[2][E])>(0==y[2][E])?1:0)||(u[2]<y[2]?-1:u[2]>y[2]?1:0)}while(0==b)}b=jb[a]=0<=b}return b}var kb={};function lb(a){return kb[a]||(kb[a]=Q&&!!q.documentMode&&q.documentMode>=a)}!Q||lb(9);!Q||lb(9);Q&&R("8");!ab||R("528");$a&&R("1.9b")||Q&&R("8")||Za&&R("9.5")||ab&&R("528");$a&&!R("8")||Q&&R("9");function mb(){}mb[F].la=j;function nb(a,b){this.type=a;this.target=b;ba(this,this.target)}nb[F].U=j;nb[F].W=g;var ob={},S={},pb={},qb={};
function rb(a,b,c,d,f){if("array"==na(b)){for(var e=0;e<b[E];e++)rb(a,b[e],c,d,f);return i}d=!!d;a:{e=S;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ra(a),e[a]))){a=e[a];break a}a=i}if(!a)return j;for(e=0;e<a[E];e++)if(a[e].Pa==c&&a[e].ia==d&&a[e].Oa==f)return sb(a[e].key);return j}
function sb(a){if(!ob[a])return j;var b=ob[a];if(b.V)return j;var c=b.src,d=b[C],f=b.Da,e=b.ia;c.removeEventListener?(c==K||!c.ka)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in qb?qb[d]:qb[d]="on"+d,f);c=ra(c);pb[c]&&(f=pb[c],Ia(f,b),0==f[E]&&delete pb[c]);b.V=g;if(b=S[d][e][c])b.ea=g,tb(d,e,c,b);delete ob[a];return g}
function tb(a,b,c,d){if(!d.M&&d.ea){for(var f=0,e=0;f<d[E];f++)d[f].V?d[f].Da.src=i:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.ea=j;0==e&&(delete S[a][b][c],S[a][b].D--,0==S[a][b].D&&(delete S[a][b],S[a].D--),0==S[a].D&&delete S[a])}}function ub(a,b,c,d,f){var e=1,b=ra(b);if(a[b]){a.G--;a=a[b];a.M?a.M++:a.M=1;try{for(var h=a[E],k=0;k<h;k++){var o=a[k];if(o&&!o.V){var t=e,u,y=o,Ob=f;y.Ma&&sb(y.key);u=y.handleEvent(Ob);e=t&u!==j}}}finally{a.M--,tb(c,d,b,a)}}return Boolean(e)}var vb=0;
function wb(a){if(a[1]){var b=a[0],c=b[A]("#");0<=c&&(a[w](b[D](c)),a[0]=b=b[D](0,c));c=b[A]("?");0>c?a[1]="?":c==b[E]-1&&(a[1]=void 0)}return a[I]("")}var xb=/#|$/,yb=!Q||lb(9);!$a&&!Q||Q&&lb(9)||$a&&R("1.9.1");Q&&R("9");function zb(a,b){Qa(b,function(c,d){"style"==d?a.style.cssText=c:"class"==d?ca(a,c):"for"==d?a.htmlFor=c:d in Ab?a[ea](Ab[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a[ea](d,c):a[d]=c})}
var Ab={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Bb(a,b,c,d){function f(h){h&&b[v](L(h)?a.createTextNode(h):h)}for(;d<c[E];d++){var e=c[d];oa(e)&&!(qa(e)&&0<e.nodeType)?Fa(Cb(e)?Ja(e):e,f):f(e)}}
function T(a,b,c){var d=arguments,f=d[0],e=d[1];if(!yb&&e&&(e.name||e[C])){f=["<",f];e.name&&f[w](' name="',va(e.name),'"');if(e[C]){f[w](' type="',va(e[C]),'"');var h={};Sa(h,e);e=h;delete e[C]}f[w](">");f=f[I]("")}f=q[da](f);e&&(L(e)?ca(f,e):"array"==na(e)?Na[ja](i,[f].concat(e)):zb(f,e));2<d[E]&&Bb(q,f,d,2);return f}function Cb(a){if(a&&"number"==typeof a[E]){if(qa(a))return"function"==typeof a.item||"string"==typeof a.item;if(pa(a))return"function"==typeof a.item}return j}
function Db(a){this.Q=a||K.document||q}Db[F].B=function(a){return L(a)?this.Q.getElementById(a):a};Db[F].createElement=function(a){return this.Q[da](a)};Db[F].createTextNode=function(a){return this.Q.createTextNode(a)};Db[F].appendChild=function(a,b){a[v](b)};function Eb(){}M(Eb,mb);J=Eb[F];J.ka=g;J.S=i;J.X=function(a){this.S=a};J.removeEventListener=function(a,b,c,d){rb(this,a,b,c,d)};
J.dispatchEvent=function(a){var b=a[C]||a,c=S;if(b in c){if(L(a))a=new nb(a,this);else if(a instanceof nb)a.target=a.target||this;else{var d=a,a=new nb(b,this);Sa(a,d)}var d=1,f,c=c[b],b=g in c,e;if(b){f=[];for(e=this;e;e=e.S)f[w](e);e=c[g];e.G=e.D;for(var h=f[E]-1;!a.U&&0<=h&&e.G;h--)ba(a,f[h]),d&=ub(e,f[h],a[C],g,a)&&a.W!=j}if(j in c)if(e=c[j],e.G=e.D,b)for(h=0;!a.U&&h<f[E]&&e.G;h++)ba(a,f[h]),d&=ub(e,f[h],a[C],j,a)&&a.W!=j;else for(f=this;!a.U&&f&&e.G;f=f.S)ba(a,f),d&=ub(e,f,a[C],j,a)&&a.W!=j;
a=Boolean(d)}else a=g;return a};function Fb(){}ma(Fb);Fb[F].Ca=0;Fb.F();function U(a){this.Na=a||La||(La=new Db);this.Ea=Gb}M(U,Eb);U[F].qa=Fb.F();var Gb=i;function Hb(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close"}throw n("Invalid component state");}J=U[F];J.aa=i;J.ba=j;J.A=i;
J.Ea=i;J.T=i;J.P=i;J.J=i;J.getId=function(){return this.aa||(this.aa=":"+(this.qa.Ca++).toString(36))};J.B=function(){return this.A};J.X=function(a){if(this.T&&this.T!=a)throw n("Method not supported");U.u.X[H](this,a)};J.L=function(){Ib(this,function(a){a.ba&&a.L()});this.pa&&this.pa.Qa();this.ba=j};function Ib(a,b,c){a.P&&Fa(a.P,b,c)}
J.removeChild=function(a,b){if(a){var c=L(a)?a:a.getId(),a=this.J&&c?(c in this.J?this.J[c]:void 0)||i:i;if(c&&a){var d=this.J;c in d&&delete d[c];Ia(this.P,a);b&&(a.L(),a.A&&a.A&&a.A.parentNode&&a.A.parentNode.removeChild(a.A));c=a;if(c==i)throw n("Unable to set parent component");c.T=i;U.u.X[H](c,i)}}if(!a)throw n("Child is not in parent component");return a};vb++;function V(){}var Jb;ma(V);J=V[F];
J.K=function(a,b,c){if(a=a.B?a.B():a)if(Q&&!R("7")){var d=Kb(this,Ma(a),b);d[w](b);ua(c?Na:Oa,a)[ja](i,d)}else c?Na(a,b):Oa(a,b)};J.ga=function(a,b){var c;if(a.I&32&&(c=a.R())){if(!b&&a.j&32){try{c.blur()}catch(d){}a.j&32&&(a.Y&4&&a.I&4&&a.setActive(j),a.Y&32&&a.I&32&&Lb(a,32,j)&&a.C(32,j))}var f;(f=c.getAttributeNode("tabindex"))&&f.specified?(f=c.tabIndex,f="number"==typeof f&&0<=f&&32768>f):f=j;f!=b&&(b?c.tabIndex=0:(c.tabIndex=-1,c.removeAttribute("tabIndex")))}};
J.C=function(a,b,c){var d=a.B();if(d){var f;this.Z||(f=this.$(),this.Z={1:f+"-disabled",2:f+"-hover",4:f+"-active",8:f+"-selected",16:f+"-checked",32:f+"-focused",64:f+"-open"});(f=this.Z[b])&&this.K(a,f,c);this.O(d,b,c)}};J.O=function(a,b,c){Jb||(Jb={1:"disabled",8:"selected",16:"checked",64:"expanded"});(b=Jb[b])&&a[ea]("aria-"+b,c)};J.R=function(a){return a.B()};J.$=function(){return"goog-control"};
function Kb(a,b,c){var d=[];c&&(b=b.concat([c]));Fa([],function(f){Ha(f,ua(O,b))&&(!c||O(f,c))&&d[w](f[I]("_"))});return d}function W(){}M(W,V);ma(W);W[F].O=function(a,b,c){16==b?a[ea]("aria-pressed",c):W.u.O[H](this,a,b,c)};W[F].$=function(){return"goog-button"};Q||ab&&R("525");function Mb(a,b){if(!a)throw n("Invalid class name "+a);if(!pa(b))throw n("Invalid decorator function "+b);}var Nb={};
function X(a,b,c){U[H](this,c);if(!b){for(var b=this.constructor,d;b;){d=ra(b);if(d=Nb[d])break;b=b.u?b.u.constructor:i}b=d?pa(d.F)?d.F():new d:i}this.H=b;this.ja=a}M(X,U);J=X[F];J.ja=i;J.j=0;J.I=39;J.Y=255;J.Ja=0;J.Ka=g;J.g=i;J.R=function(){return this.H.R(this)};J.K=function(a,b){b?a&&(this.g?O(this.g,a)||this.g[w](a):this.g=[a],this.H.K(this,a,g)):a&&this.g&&(Ia(this.g,a),0==this.g[E]&&(this.g=i),this.H.K(this,a,j))};
J.L=function(){X.u.L[H](this);this.ra&&this.ra.detach();this.Ka&&!(this.j&1)&&this.H.ga(this,j)};J.setActive=function(a){Lb(this,4,a)&&this.C(4,a)};J.C=function(a,b){this.I&a&&b!=!!(this.j&a)&&(this.H.C(this,a,b),this.j=b?this.j|a:this.j&~a)};function Lb(a,b,c){return!!(a.I&b)&&!!(a.j&b)!=c&&(!(a.Ja&b)||a.dispatchEvent(Hb(b,c)))&&!a.la}if(!pa(X))throw n("Invalid component class "+X);if(!pa(V))throw n("Invalid renderer class "+V);var Pb=ra(X);Nb[Pb]=V;Mb("goog-control",function(){return new X(i)});
function Y(){}M(Y,W);ma(Y);Y[F].ga=la;Y[F].C=function(a,b,c){Y.u.C[H](this,a,b,c);if((a=a.B())&&1==b)a.disabled=c};Y[F].O=la;function Qb(a,b,c){X[H](this,a,b||Y.F(),c)}M(Qb,X);Mb("goog-button",function(){return new Qb(i)});Q&&R(8);
function Rb(a,b,c){a=a||q;c=c&&"*"!=c?c.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(c||b))b=a.querySelectorAll(c+(b?"."+b:""));else if(b&&a.getElementsByClassName)if(a=a.getElementsByClassName(b),c){for(var d={},f=0,e=0,h;h=a[e];e++)c==h.nodeName&&(d[f++]=h);d.length=f;b=d}else b=a;else if(a=a.getElementsByTagName(c||"*"),b){d={};for(e=f=0;h=a[e];e++)c=h.className,"function"==typeof c[G]&&O(c[G](/\s+/),b)&&(d[f++]=h);d.length=f;b=d}else b=a;if(1<=b[E])return b[0];throw n();}
function Sb(a){return q.createTextNode(a)}if(void 0===m._LOGIN_URL){var Tb;m._IS_MULTILOGIN_ENABLED?(Tb=Ub("AddSession",g),Tb+="&Email="+l(_USER_EMAIL)):Tb=Ub("ServiceLogin",g);_LOGIN_URL=Tb}function Vb(a,b){if(b instanceof r){for(var c=0;c<b[E];c++)a=a[z]("%"+(c+1),b[c]);return a}return a[z]("%1",b)}
var Wb=RegExp("<(/s*(blockquote|body|center|dd|dir|div|dl|dt|form|h1|h2|h3|h4|h5|h6|head|html|hr|isindex|li|menu|noframes|ol|p|table|td|th|tr|title|ul)[^>]*|s*br[^>]*)>","gi"),Xb=/<[^>]*>/gi,Yb=/</g,Zb=/>/g;function $b(a,b){if(!a)return"";b&&(a=a[z](Wb," "));a=a[z](Xb,"");return a[z](Yb,"&lt;")[z](Zb,"&gt;")}function ac(a,b){if(a[E]<=b)return a;for(var c=a[G](/\s+/),d=[],f=0,e=0;e<c[E]&&f<=b;e++)d[w](c[e]),f+=c[e][E]+(e?1:0);a=d[I](" ");e!=c[E]&&(a+="...");return a}var bc={};
function cc(a){if(!(a in bc)){var b=bc,c;c=m[ha].search;var d=c.search(xb),f;b:{f=0;for(var e=a[E];0<=(f=c[A](a,f))&&f<d;){var h=c.charCodeAt(f-1);if(38==h||63==h)if(h=c.charCodeAt(f+e),!h||61==h||38==h||35==h)break b;f+=e+1}f=-1}if(0>f)c=i;else{e=c[A]("&",f);if(0>e||e>d)e=d;f+=a[E]+1;c=decodeURIComponent(c[D](f,e-f)[z](/\+/g," "))}b[a]=c}return bc[a]}function dc(a){cc("hl")&&(a=wb([a,"&","hl","=",l("en")]));var b=cc("gl");b&&(a=wb([a,"&","gl","=",l(p(b))]));return a}
function Ub(a,b){var c="https://www.google.com/accounts/"+a+"?service=reader&passive=true&nui=1&ltmpl=default";if(b){var d;try{d=m.top[ha][ia]}catch(f){d=m[ha][ia]}c+="&continue="+l(d)+"&followup="+l(d)}return c}
var Z={},ec={blue:{k:"#fff",i:"#bccceb",z:"#090992",v:"#bccceb",o:"#1010c8",e:"#7a7ee0",h:"#e5ecf9",d:"#898de9"},green:{k:"#fff",i:"#d8dbbc",z:"#2d8509",v:"#d8dbbc",o:"#58bf2f",e:"#97e07a",h:"#f5fbeb",d:"#adb094"},slate:{k:"#123",i:"#345",z:"#5e805e",v:"#5e6f80",o:"#abc",e:"#5e6f80",h:"#152939",d:"#abc"},gray:{k:"#fff",i:"#ccc",z:"#666",v:"#ccc",o:"#999",e:"#ccc",h:"#eee",d:"#aaa"},khaki:{k:"#f2e9ca",i:"#8e7c6a",z:"#d52",v:"#cba",o:"#543",e:"#ba9",h:"#eae0c6",d:"#987"},pink:{k:"#fff",i:"#aaa",z:"#d69",
v:"#ddd",o:"#e684ad",e:"#ebc",h:"#fcf0f7",d:"#a88"},black:{k:"#000",i:"#aaa",z:"#ccc",v:"#d8dbbc",o:"#d52",e:"#7a2b0e",h:"#111",d:"#999"}},fc={margin:0,padding:0,background:"transparent none",border:"none",textAlign:"left",textIndent:"0",textDecoration:"none",fontWeight:"normal"};
function gc(a,b){var c=hc(a);$(a,c.Ba,b);if(a.ha){var d=T("h3");$(a,c.Aa,d);d[v](Sb(a.ha));b[v](d)}d=T("ul");$(a,c.za,d);for(var f=0,e;e=a.a.items[f];f++)if(e[ka]){var h=T("li");$(a,c.ya,h);var k=T("a",{href:e[ka][ia],title:e[ga],"class":"i"});$(a,c.va,k);var o=$b(e[ga]||e.content);/^[\s\xa0]*$/.test(o==i?"":p(o))||(o=ac(o,48));k[v](Sb(o));h[v](k);if(a.Ha&&!a.da&&e.origin[ga]){var t=e.origin,k=T("div",{"class":"s"});$(a,c.xa,k);h[v](k);o=t[ga];48<o[E]&&(o=o.substring(0,48));s(k,Vb("from <a>%1</a>",
o));t.htmlUrl&&(t=T("a",{href:t.htmlUrl}),s(t,o),$(a,c.wa,t),k.replaceChild(t,k.getElementsByTagName("a")[0]))}if(a.Ga&&!a.da){k="";e=e.annotations||[];for(o=0;t=e[o];o++)if(-1!=a.a.id[A](t.userId)&&0<t.content[E]){k=t.content;break}0<k[E]&&(e=T("div"),$(a,c.ua,e),48<k[E]&&(k=k.substring(0,48)),s(e,'"'+k+'"'),h[v](e))}d[v](h)}b[v](d);d=T("div",{"class":"f"});$(a,c.oa,d);a.Ia&&(f=T("a",{href:"http://www.google.com/webelements"}),$(a,c.La,f),d[v](f));if(a.a.id&&(f=-1!=a.a.id.search(/^user\/(\d+)\/bundle\//),
h=0==a.a.id.lastIndexOf("feed/",0),e=a.a[ka]&&a.a[ka][ia],!h||f||e))if(e=T("a"),$(a,c.d,e),e[v](Sb("document"in K?Ba("View all &raquo;"):Da("View all &raquo;"))),f){var u=dc("http://www.google.com/reader/bundle/"+a.a.id),f=ic({ta:u,Fa:"Preview &raquo;"});d[v](f);$(a,c.na,Rb(f,"gr-bundle-table"));$(a,c.ma,Rb(f,"gr-show-all"));Rb(f,"gr-subscribe-button").onclick=function(){m[ha].href=u}}else e.href=h?a.a[ka][ia]:dc("http://www.google.com/reader/shared/"+a.a.id),d[v](e);b[v](d)}
function hc(a){if("-"==a.fa)return{};a=ec[a.fa];return{Ba:{fontFamily:"arial, sans-serif",fontSize:"10pt",background:a.k,border:"solid 1px "+a.i,margin:"0.5em"},Aa:{padding:"0.2em 0.5em",background:a.h,borderBottom:"solid 1px "+a.v,color:a.z},za:{padding:"0.2em",margin:"0 0.5em",overflow:"hidden"},ya:{listStyleType:"none",padding:"0.4em 0 0.4em 0"},va:{color:a.o,borderBottom:"solid 1px "+a.e},xa:{color:a.e},wa:{color:a.e},ua:{color:"#777",fontStyle:"italic"},oa:{textAlign:"right",borderTop:"solid 1px "+
a.i,background:a.h,padding:"0.2em 8px",fontSize:"small",whiteSpace:"nowrap",overflow:"hidden"},d:{color:a.d,textDecoration:"underline"},na:{width:"100%"},ma:{textAlign:"right"},La:{cssFloat:"left",styleFloat:"left",display:"block",width:"130px",height:"20px",background:Q&&7>ib?"none":"url(http://www.google.com/reader/ui/web-elements-logo.png)",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src=http://www.google.com/reader/ui/web-elements-logo.png,sizingMethod=crop)"}}}
function $(a,b,c){if(b){for(var d in fc)c.style[d]=fc[d];for(var f in b)c.style[f]=b[f]}}m.GRC_p=function(a){Z=a};
m.GRC=function(a,b){"GRC_c"in m||(m.GRC_c=0);this.N="readerpublishermodule"+m.GRC_c++;this.a=a;this.fa=Z.c;this.ha=Z.t;this.Ha="true"==Z.s;this.da="true"==Z.b;this.Ga="true"==Z.n;this.Ia="true"==Z.w;if(b)s(b,""),b.id=this.N,gc(this,q.getElementById(this.N));else{q.write('<div id="'+this.N+'" class="reader-publisher-module"></div>');var c=this;m.setTimeout(function(){gc(c,q.getElementById(c.N))},0)}};function ic(a){var b='<div><table class="gr-bundle-table"><tr><td><input class="gr-subscribe-button" type="button" value="Subscribe"></td><td class="gr-show-all"><a href="'+va(p(a.ta))+'">'+a.Fa+"</a></td></tr></table></div>",a=q[da]("div");Q?(s(a,"<br>"+b),a.removeChild(a[B])):s(a,b);if(1==a.childNodes[E])a=a.removeChild(a[B]);else{for(b=q.createDocumentFragment();a[B];)b[v](a[B]);a=b}return a};})();